version: "2.4"
services:
  piwigo:
    image: linuxserver/piwigo:latest
    container_name: piwigo
    depends_on:
      - mariadb
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
    volumes:
      - piwigo:/config
    ports:
      - 80:80
    restart: unless-stopped
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: mariadb
    env_file:
      - secrets/mariadb.env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      MYSQL_DATABASE: piwigo
      MYSQL_USER: piwigo
    volumes:
      - mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
  # seafile:
  #   container_name: seafile
  #   image: skycoder42/seafile:latest
  #   build:
  #     context: seafile
  #     args:
  #       SEAFILE_VERSION: 8.0.4
  #       LIBSEARPC_VERSION: 3.2-latest
  #   env_file:
  #     - secrets/seafile.env
  #   volumes:
  #     - seafile_config:/root/.ccnet
  #     - seafile_data:/seafile/seafile-data
  #     - seafile_libraries:/seafile/libraries
  #   restart: unless-stopped
  piwigo_sync:
    container_name: piwigo_sync
    depends_on:
      - piwigo
    image: skycoder42/piwigo_sync:latest
    build:
      context: piwigo_sync
    env_file:
      - secrets/piwigo_sync.env
    environment:
      PIWIGO_HOST: piwigo
      PIWIGO_PORT: 80
      SYNC_INTERVAL: 1
    restart: unless-stopped
volumes:
  piwigo:
  mariadb:
  seafile_config:
  seafile_data:
  seafile_libraries:
