name: piwigo_sync
description: A simple command-line application.
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0
  meta: ^1.2.3
  html: ^0.14.0+4

dev_dependencies:
  lint: ^1.3.0
  dart_pre_commit: ^1.0.2

