name: piwigo_sync
description: A simple command-line application.
environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0
dev_dependencies:
  lint: ^1.3.0
  git_hooks: ^0.0.4
  dart_pre_commit: ^1.0.2

